#端口
server:
  port: 8080
#热部署
debug: true
#配置数据源
spring:
  #热部署
  devtools:
    restart:
      enabled: true #设置开启热部署
    freemarker:
      cache: false #页面不加载缓存，修改即时生效
  #数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.111.1:3306/erp_zzh?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
      username: root
      password: admin
      max-active: 20  #最大空闲数
      max-wait: 5000 #最大等待毫秒数
      initial-size: 1 #定义初始连接数
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j,wall
      validation-query: SELECT 'x' #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: admin
        allow:
        deny:
        url-pattern: /druid/*
      #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
    characterEncoding: UTF-8
      #jsonFormat的作用，时间json数据化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



